server:
  port: 8888
spring:
  # hikariPool
  datasource:
    username: root
    password: Duxiaoyu@123
    url: jdbc:mysql://139.224.81.29/mybatis_rabbit_plug?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true

# mybatis
mybatis:
  mapper-locations: classpath:com.mybatis-rabbit-plug.core.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
  type-handlers-package: com.rabbit.starter.typehandler